### ISSUE TITLE
ArcanePepper733 broke block too fast: break time: 100; should: 93 for Dirt with ItemDiamondShovel

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#488] opened 2019-01-02 01:35 UTC
**Describe the bug**
Break grass/dirt with a diamond shovel and get an error. I think this happens on blocks other than dirt and diamond shovel use to break

**To Reproduce**
1. Open Minecraft
3. Break dirt with diamond shovel

**Expected behavior**
No error
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**
https://pastebin.com/aPP2Q7Bb

**Comment by geNAZt** [comment] 2019-01-06 11:14
Is there some more information? I can't reproduce that issue

**Comment by geNAZt** [comment] 2019-01-06 11:19
Fixed with latest version

**Closed as completed by geNAZt** 2019-01-06 11:19 UTC
